export default {routes:[{
    path:'/demo',
    name:'demo-index',
    component:()=>import('pages/demo/index') 
},{
    path:'/list',
    name:'list-index',
    component:()=>import('pages/list/index') 
},{
    path:'/mini-program/metting-active/detail',
    name:'mini-program-metting-active-detail-index',
    component:()=>import('pages/mini-program/metting-active/detail/index') 
},{
    path:'/mini-program/metting-active/edit',
    name:'mini-program-metting-active-edit-index',
    component:()=>import('pages/mini-program/metting-active/edit/index') 
},{
    path:'/mini-program/metting-active',
    name:'mini-program-metting-active-index',
    component:()=>import('pages/mini-program/metting-active/index') 
},{
    path:'/mini-program/metting-active/join-user',
    name:'mini-program-metting-active-join-user-index',
    component:()=>import('pages/mini-program/metting-active/join-user/index') 
}]}