export default {routes:[{
    path:'/demo',
    name:'demo',
    component:()=>import('pages/demo') 
},{
    path:'/list',
    name:'list',
    component:()=>import('pages/list') 
},{
    path:'/operate',
    name:'operate',
    component:()=>import('pages/operate/operate.vue') 
},{
    path:'/operateDetail',
    name:'operateDetail',
    component:()=>import('pages/operate/operateDetail.vue')
},{
    path:'/order',
    name:'order',
    component:()=>import('pages/order/order.vue') 
},{
    path:'/orderDetail',
    name:'orderDeatil',
    component:()=>import('pages/order/orderDetail.vue')
},{
    path:'/setting',
    name:'setting',
    component:()=>import('pages/setting/setting.vue') 
},{
    path:'/settingDetail',
    name:'settingDetail',
    component:()=>import('pages/setting/settingDetail.vue')
},{
    path:'/newBuiltGoods',
    name:'newBuiltGoods',
    component:()=>import('pages/setting/newBuiltGoods.vue')
},{
    path:'/editGoods',
    name:'edutGoods',
    component:()=>import('pages/setting/editGoods.vue')
},{  
    path:'/mini-program/metting-active/detail',
    name:'mini-program-metting-active-detail',
    component:()=>import('pages/mini-program/metting-active/detail') 
},{
    path:'/mini-program/metting-active/edit',
    name:'mini-program-metting-active-edit',
    component:()=>import('pages/mini-program/metting-active/edit') 
},{
    path:'/mini-program/metting-active',
    name:'mini-program-metting-active',
    component:()=>import('pages/mini-program/metting-active') 
}]}